<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Data Pegawai</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 8px;
            color: #333;
        }

        h1 {
            text-align: center;
            color: #1565c0;
            margin-bottom: 5px;
            font-size: 14px;
        }

        .subtitle {
            text-align: center;
            color: #666;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 3px;
            text-align: left;
        }

        th {
            background-color: #1565c0;
            color: white;
            font-weight: bold;
            font-size: 7px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .text-right {
            text-align: right;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #999;
        }

        .summary {
            margin-bottom: 10px;
            padding: 8px;
            background-color: #e3f2fd;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <h1>Data Pegawai</h1>
    <p class="subtitle">Diekspor pada {{ now()->format('d M Y H:i') }}</p>

    <div class="summary">
        <strong>Total Pegawai:</strong> {{ $total }}
    </div>

    <table>
        <thead>
            <tr>
                <th width="3%">No</th>
                <th width="10%">NIP</th>
                <th width="14%">Nama</th>
                <th width="3%">JK</th>
                <th width="6%">Golongan</th>
                <th width="14%">Jabatan</th>
                <th width="14%">SKPD</th>
                <th width="10%">UPT</th>
                <th width="6%">Mk (Thn)</th>
                <th width="10%">Pendidikan</th>
                <th width="10%">Gaji Pokok</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $item['nip'] ?? '-' }}</td>
                    <td>{{ $item['nama'] ?? '-' }}</td>
                    <td>{{ str_contains($item['jk'] ?? '', 'LAKI') ? 'L' : 'P' }}</td>
                    <td>{{ $item['golru'] ?? '-' }}</td>
                    <td>{{ $item['jabatan'] ?? '-' }}</td>
                    <td>{{ $item['skpd']['nama_skpd'] ?? '-' }}</td>
                    <td>{{ $item['upt'] ?? '-' }}</td>
                    <td>{{ ($item['mk_thn'] ?? 0) }} thn</td>
                    <td>{{ $item['tk_ijazah'] ?? '-' }}</td>
                    <td class="text-right">{{ number_format($item['gapok'] ?? 0, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Dashboard PW
    </div>
</body>

</html>